openapi: 3.0.2
info:
  description: A web application to know which food and books you have and where they are
  version: 1.0.0
  title: Inventory Manager
  contact:
    email: biral.mattia@gmail.com
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
servers:
  - url: https://inventorymanager.ddns.net/api/
  - url: https://inventorymanager.my.to/api/
  - url: https://inventorymanager.8bit.ca/api/
tags:
  - name: feedbacks
    description: Handles form feedbacks
  - name: temp-users
    description: Handles registration and confirmation requests
  - name: auth
    description: Handles user authentication
  - name: settings
    description: Handles user settings
  - name: locations
    description: Handles locations
  - name: products
    description: Handles products
  - name: stocks
    description: Handles stocks
  - name: categories
    description: Handles categories
  - name: books
    description: Handles books
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: simplychat-auth
  schemas:
    username:
      type: string
      example: Pyrix25633
      minLength: 3
      maxLength: 32
    email:
      type: string
      format: email
      example: name.surname@domain.com
    password:
      type: string
      example: passwd1234@
      minLength: 8
    token:
      type: string
      example: 4b135f35634c8f34258551d907f179a1d2847a2e6a55f54d399b3a0928294a5f30c842bf2ebcf2aad96769d6c3e50f216d386c15b3caebc07ec72696577a1d01
      minLength: 128
      maxLength: 128
    tfaKey:
      type: string
      example: NUZSQS3CNRMGYJBJNATFI2BIJ4QUGULDKNKDS6CGJ5XWC4B4KIRQ
      minLength: 52
      maxLength: 52
    tfaCode:
      type: integer
      minimum: 100000
      maximum: 999999
      example: 190347
    id:
      type: integer
      example: 26
      minimum: 1
    customization:
      type: object
      properties:
        compactMode:
          type: boolean
          example: false
        condensedFont:
          type: boolean
          example: false
        aurebeshFont:
          type: boolean
          example: false
        sharpMode:
          type: boolean
          example: false
      required:
        - compactMode
        - condensedFont
        - aurebeshFont
        - sharpMode
    sessionDuration:
      type: integer
      example: 14
      minimum: 5
      maximum: 90
    base64Image:
      type: string
      example: "data:image/svg+xml;base64,czY0OGI0bmcxNjViMjYrc3NjNDF2ZjJhKzR3ZjF2Y2EyYSsx..."
    name:
      type: string
      minLength: 3
      maxLength: 32
    title:
      type: string
      minLength: 3
      maxLength: 32
    quantity:
      type: integer
      example: 3
      minimum: 1
    unitOfMeasurement:
      type: string
      enum:
        - PIECES
        - GRAMS
        - MILLILITERS
    date:
      type: string
      example: '2024/12/04'
      minLength: 8
      maxLength: 10
    page:
      type: integer
      example: 2
      minimum: 0
    pages:
      type: integer
      example: 3
      minimum: 1
    orderValue:
      type: object
      additionalProperties:
        type: array
        items:
          oneOf:
            - type: string
              enum:
                - asc
                - desc
            - $ref: "#/components/schemas/orderValue"
    order:
      type: array
      items:
        type: object
        $ref: "#/components/schemas/orderValue"
paths:
  /feedbacks/register-username:
    get:
      tags:
        - feedbacks
      summary: Username feedback for the registration form
      description: Returns a user friendly username feedback
      operationId: feedbacks/register-username
      parameters:
        - in: query
          name: username
          schema:
            $ref: "#/components/schemas/username"
          description: The username, it can be invalid
          required: true
      responses:
        "200":
          description: Username feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Username
  /feedbacks/register-email:
    get:
      tags:
        - feedbacks
      summary: Email feedback for the registration form
      description: Returns a user friendly email feedback
      operationId: feedbacks/register-email
      parameters:
        - in: query
          name: email
          schema:
            $ref: "#/components/schemas/email"
          description: The email, it can be invalid
          required: true
      responses:
        "200":
          description: Email feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Email
  /feedbacks/confirm-username:
    get:
      tags:
        - feedbacks
      summary: Username feedback for the confirmation form
      description: Returns a user friendly username feedback
      operationId: feedbacks/confirm-username
      parameters:
        - in: query
          name: username
          schema:
            $ref: "#/components/schemas/username"
          description: The username
          required: true
      responses:
        "200":
          description: Username feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Username
        "400":
          description: Bad Request
  /feedbacks/login-username:
    get:
      tags:
        - feedbacks
      summary: Username feedback for the login form
      description: Returns a user friendly username feedback
      operationId: feedbacks/login-username
      parameters:
        - in: query
          name: username
          schema:
            $ref: "#/components/schemas/username"
          description: The username
          required: true
      responses:
        "200":
          description: Username feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Username
        "400":
          description: Bad Request
  /feedbacks/location-name:
    get:
      tags:
        - feedbacks
      summary: Location's name feedback for the location creation form
      description: Returns a user friendly location's name feedback
      operationId: feedbacks/location-name
      parameters:
        - in: query
          name: name
          schema:
            $ref: "#/components/schemas/name"
          description: The location's name
          required: true
      responses:
        "200":
          description: Location's name feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Name
        "400":
          description: Bad Request
  /feedbacks/product-name:
    get:
      tags:
        - feedbacks
      summary: Product's name feedback for the product creation form
      description: Returns a user friendly product's name feedback
      operationId: feedbacks/product-name
      parameters:
        - in: query
          name: name
          schema:
            $ref: "#/components/schemas/name"
          description: The product's name
          required: true
      responses:
        "200":
          description: Product's name feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Name
        "400":
          description: Bad Request
  /feedbacks/category-name:
    get:
      tags:
        - feedbacks
      summary: Category's name feedback for the category's creation form
      description: Returns a user friendly category's name feedback
      operationId: feedbacks/category-name
      parameters:
        - in: query
          name: name
          schema:
            $ref: "#/components/schemas/name"
          description: The category's name
          required: true
      responses:
        "200":
          description: Category's name feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
                    example: Valid Name
        "400":
          description: Bad Request
  /temp-users:
    post:
      tags:
        - temp-users
      summary: Creates a new temporary user
      description: First step of the registration process
      operationId: temp-users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: "#/components/schemas/username"
                email:
                  $ref: "#/components/schemas/email"
                password:
                  $ref: "#/components/schemas/password"
              required:
                - username
                - email
                - password
      responses:
        "201":
          description: The first step of the registration succeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    $ref: "#/components/schemas/username"
        "400":
          description: Bad Request
        "422":
          description: "Unprocessable Content: temporary user cannot be created because of duplicate username or email"
  /temp-users/{username}/confirm:
    post:
      tags:
        - temp-users
      summary: Confirms a temporary user
      description: Sencond and last step of the registration process
      operationId: temp-users/[username]/confirm
      parameters:
        - in: path
          name: username
          schema:
            $ref: "#/components/schemas/username"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                verificationCode:
                  type: integer
                  minimum: 100000
                  maximum: 999999
                  example: 190347
              required:
                - verificationCode
      responses:
        "201":
          description: The second step of the registration succeded, user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    example: 10
        "400":
          description: Bad Request
        "404":
          description: "Not Found: no temporary users found with specified username"
        "422":
          description: "Unprocessable Content: user cannot be created"
  /auth/validate-token:
    get:
      tags:
        - auth
      summary: Used by client to check whether the user needs to log in
      description: Gets a boolean feedback
      operationId: auth/validate-token
      responses:
        "200":
          description: If true the cookie token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
  /auth/login:
    post:
      tags:
        - auth
      summary: Logs the user in if 2FA is not needed
      description: Sets the authentication cookie if 2FA is not needed
      operationId: auth/login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: "#/components/schemas/username"
                password:
                  $ref: "#/components/schemas/password"
              required:
                - username
                - password
      responses:
        "200":
          description: First authentication step succeded, 2FA is needed
          content:
            application/json:
              schema:
                type: object
                properties:
                  tfaToken:
                    $ref: "#/components/schemas/token"
        "204":
          description: Authentication succeded
          headers:
            Set-Cookie:
              schema:
                type: string
                example: >
                  Set-Cookie: simplychat-auth=...; Path=/; SameSite=Strict; Expires=Tue 09 Apr 2024 11:39:56 GMT
              description: Sets authentication cookie
        "400":
          description: Bad Request
        "401":
          description: "Unauthorized: wrong password"
        "404":
          description: "Not Found: no users found with specified username"
  /auth/login-tfa:
    post:
      tags:
        - auth
      summary: Logs the user in
      description: Sets the authentication cookie
      operationId: auth/login-tfa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tfaToken:
                  $ref: "#/components/schemas/token"
                tfaCode:
                  $ref: "#/components/schemas/tfaCode"
              required:
                - tfaToken
                - tfaCode
      responses:
        "204":
          description: Authentication succeded
          headers:
            Set-Cookie:
              schema:
                type: string
                example: >
                  Set-Cookie: simplychat-auth=...; Path=/; SameSite=Strict; Expires=Tue 09 Apr 2024 11:39:56 GMT
              description: Sets authentication cookie
        "400":
          description: Bad Request
        "401":
          description: "Unauthorized: wrong tfaCode"
        "404":
          description: "Not Found: no pending 2FA actions found with specified tfaToken"
        "422":
          description: "Unprocessable Content: user disabled 2FA and this step is not needed"
  /auth/tfa/generate-key:
    get:
      tags:
        - auth
      summary: Used by client to generate a new 2FA key
      description: Called when activating 2FA in user settings
      operationId: auth/tfa/generate-key
      responses:
        "200":
          description: New 2FA key and QR
          content:
            application/json:
              schema:
                type: object
                properties:
                  tfaKey:
                    $ref: "#/components/schemas/tfaKey"
                  tfaQr:
                    $ref: "#/components/schemas/base64Image"
        "401":
          description: Unauthorized
  /auth/tfa/validate-code:
    get:
      tags:
        - auth
      summary: Used by the client to verify that the user correctly scanned the QR
      description: Gets a boolean feedbacks
      operationId: auth/tfa/validate-code
      parameters:
        - in: query
          name: tfaKey
          schema:
            $ref: "#/components/schemas/tfaKey"
          required: true
        - in: query
          name: tfaCode
          schema:
            $ref: "#/components/schemas/tfaCode"
          required: true
      responses:
        "200":
          description: If true the user has correctly scanned the QR and saved a new totp
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
        "400":
          description: Bad Request
  /auth/logout:
    post:
      tags:
        - auth
      summary: Logs the user out
      description: Unsets the authentication cookie
      operationId: auth/logout
      responses:
        "204":
          description: Logout successful
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "Set-Cookie: simplychat-auth=; Expires=Thu 01 Jan 1970 00:00:00 GMT"
              description: Unsets authentication cookie
  /auth/regenerate-token:
    post:
      tags:
        - auth
      summary: Logs the user out from all devices
      description: Unsets the authentication cookie and invalidates all sessions
      operationId: auth/regenerate-token
      responses:
        "204":
          description: Token regenerated succesfully
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "Set-Cookie: simplychat-auth=; Expires=Thu 01 Jan 1970 00:00:00 GMT"
              description: Unsets authentication cookie
        "401":
          description: Unauthorized
  /settings:
    get:
      tags:
        - settings
      summary: Gets the user's settings
      description: Returns an object with all user's settings
      operationId: settings(get)
      responses:
        "200":
          description: User's settings
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
                  username:
                    $ref: "#/components/schemas/username"
                  email:
                    $ref: "#/components/schemas/email"
                  customization:
                    $ref: "#/components/schemas/customization"
                  sessionExpiration:
                    type: integer
                    example: 1715960830
                  sessionDuration:
                    $ref: "#/components/schemas/sessionDuration"
                  tfa:
                    type: boolean
        "401":
          description: Unauthorized
    patch:
      tags:
        - settings
      summary: Modifies the user's settings
      description: Allows the user to modifies its settings, username, password, ...
      operationId: settings(patch)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  $ref: "#/components/schemas/username"
                email:
                  $ref: "#/components/schemas/email"
                customization:
                  $ref: "#/components/schemas/customization"
                password:
                  $ref: "#/components/schemas/password"
                oldPassword:
                  $ref: "#/components/schemas/password"
                sessionDuration:
                  $ref: "#/components/schemas/sessionDuration"
                tfaKey:
                  oneOf:
                    - $ref: "#/components/schemas/tfaKey"
                    - nullable: true
              required:
                - username
                - email
                - status
                - customization
                - oldPassword
                - sessionDuration
      responses:
        "204":
          description: Settings updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: wrong oldPassword"
  /settings/customization:
    get:
      tags:
        - settings
      summary: Gets the user's customization
      description: Returns an object with user's customization
      operationId: settings/customization
      responses:
        "200":
          description: User's customization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/customization"
        "401":
          description: Unauthorized
  /locations:
    get:
      tags:
        - locations
      summary: Gets all locations
      description: Returns all locations owned by the user
      operationId: locations(get)
      parameters:
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
      responses:
        "200":
          description: All locations of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  locations:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        name:
                          $ref: "#/components/schemas/name"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - locations
      summary: Creates a new location
      description: Creates a new location
      operationId: locations(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
              required:
                - name
      responses:
        "201":
          description: Location created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: location cannot be created"
  /locations/{locationId}:
    get:
      tags:
        - locations
      summary: Gets location
      description: Returns the location's name
      operationId: locations/[locationId](get)
      parameters:
        - in: path
          name: locationId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: Name
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    $ref: "#/components/schemas/name"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested location"
        "404":
          description: "Not Found: no locations found with specified locationId"
    patch:
      tags:
        - locations
      summary: Modifies the location
      description: Updates the location's name
      operationId: locations/[locationId](patch)
      parameters:
        - in: path
          name: locationId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
              required:
                - name
      responses:
        "204":
          description: Location updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested location"
        "404":
          description: "Not Found: no locations found with specified locationId"
        "422":
          description: "Unprocessable Content: location cannot be updated"
  /products:
    get:
      tags:
        - products
      summary: Gets all products
      description: Returns all products owned by the user
      operationId: products(get)
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/page"
          required: false
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
            - defaultLocation:
                name: 'desc'
      responses:
        "200":
          description: All products of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        name:
                          $ref: "#/components/schemas/name"
                        defaultQuantity:
                          $ref: "#/components/schemas/quantity"
                        defaultUnitOfMeasurement:
                          $ref: "#/components/schemas/unitOfMeasurement"
                        defaultLocation:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                  pages:
                    $ref: "#/components/schemas/pages"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - products
      summary: Creates a new product
      description: Creates a new product
      operationId: products(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultQuantity:
                  $ref: "#/components/schemas/quantity"
                defaultUnitOfMeasurement:
                  $ref: "#/components/schemas/unitOfMeasurement"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultQuantity
                - defaultUnitOfMeasurement
                - defaultLocationId
      responses:
        "201":
          description: Product created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: product cannot be created"
  /products/{productId}:
    get:
      tags:
        - products
      summary: Gets product
      description: Returns products's name, defaultQuantity, defaultUnitOfMeasurement and defaultLocationId
      operationId: products/[productId](get)
      parameters:
        - in: path
          name: productId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: Name, defaultQuantity, defaultUnitOfMeasurement and defaultLocationId
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    $ref: "#/components/schemas/name"
                  defaultQuantity:
                    $ref: "#/components/schemas/quantity"
                  defaultUnitOfMeasurement:
                    $ref: "#/components/schemas/unitOfMeasurement"
                  defaultLocationId:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested product"
        "404":
          description: "Not Found: no products found with specified productId"
    patch:
      tags:
        - products
      summary: Modifies the product
      description: Updates the product's name, defaultQuantity, defaultUnitOfMeasurement and defaultLocationId
      operationId: products/[productId](patch)
      parameters:
        - in: path
          name: productId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultQuantity:
                  $ref: "#/components/schemas/quantity"
                defaultUnitOfMeasurement:
                  $ref: "#/components/schemas/unitOfMeasurement"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultQuantity
                - defaultUnitOfMeasurement
                - defaultLocationId
      responses:
        "204":
          description: Product updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested product"
        "404":
          description: "Not Found: no products found with specified productId"
        "422":
          description: "Unprocessable Content: product cannot be updated"
  /stocks:
    get:
      tags:
        - stocks
      summary: Gets all stocks
      description: Returns all stocks owned by the user
      operationId: stocks(get)
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/page"
          required: false
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
            - defaultLocation:
                name: 'desc'
      responses:
        "200":
          description: All stocks of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  stocks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        expiration:
                           $ref: "#/components/schemas/date"
                        product:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                        quantity:
                          $ref: "#/components/schemas/quantity"
                        unitOfMeasurement:
                          $ref: "#/components/schemas/unitOfMeasurement"
                        location:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                  pages:
                    $ref: "#/components/schemas/pages"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - stocks
      summary: Creates a new stock
      description: Creates a new stock
      operationId: stocks(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                expiration:
                  $ref: "#/components/schemas/date"
                productId:
                  $ref: "#/components/schemas/id"
                quantity:
                  $ref: "#/components/schemas/quantity"
                unitOfMeasurement:
                  $ref: "#/components/schemas/unitOfMeasurement"
                locationId:
                  $ref: "#/components/schemas/id"
              required:
                - expiration
                - productId
                - quantity
                - unitOfMeasurement
                - locationId
      responses:
        "201":
          description: Stock created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: stock cannot be created"
  /stocks/{stockId}:
    get:
      tags:
        - stocks
      summary: Gets stock
      description: Returns stock's expiration, productId, quantity, unitOfMeasurement and locationId
      operationId: stocks/[stocksId](get)
      parameters:
        - in: path
          name: stockId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: Expiration, productId, quantity, unitOfMeasurement and locationId
          content:
            application/json:
              schema:
                type: object
                properties:
                  expiration:
                    $ref: "#/components/schemas/date"
                  productId:
                    $ref: "#/components/schemas/id"
                  quantity:
                    $ref: "#/components/schemas/quantity"
                  unitOfMeasurement:
                    $ref: "#/components/schemas/unitOfMeasurement"
                  locationId:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested stock"
        "404":
          description: "Not Found: no stocks found with specified stockId"
    patch:
      tags:
        - stocks
      summary: Modifies the stock
      description: Updates the stock's expiration, productId, quantity, unitOfMeasurement and locationId
      operationId: stocks/[stockId](patch)
      parameters:
        - in: path
          name: stockId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                expiration:
                  $ref: "#/components/schemas/date"
                productId:
                  $ref: "#/components/schemas/id"
                quantity:
                  $ref: "#/components/schemas/quantity"
                unitOfMeasurement:
                  $ref: "#/components/schemas/unitOfMeasurement"
                locationId:
                  $ref: "#/components/schemas/id"
              required:
                - expiration
                - productId
                - quantity
                - unitOfMeasurement
                - locationId
      responses:
        "204":
          description: Stock updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested stock"
        "404":
          description: "Not Found: no stocks found with specified stockId"
        "422":
          description: "Unprocessable Content: stock cannot be updated"
    delete:
      tags:
        - stocks
      summary: Deletes stock
      description: Removes the stock
      operationId: stocks/[stockId](delete)
      parameters:
        - in: path
          name: stockId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "204":
          description: Stock deleted succesfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested stock"
        "404":
          description: "Not Found: no stocks found with specified stockId"
  /stocks/{stockId}/remove:
    post:
      tags:
        - stocks
      summary: Decreases stock's quantity
      description: Decreases stock's quantity by 1 if unitOfMeasurement is 'PIECES', by 10 otherwise
      operationId: stocks/[stockId]/remove
      parameters:
        - in: path
          name: stockId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "204":
          description: Stock quantity decreased successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested stock"
        "404":
          description: "Not Found: no stocks found with specified stockId"
        "422":
          description: "Unprocessable Content: stock quantity cannot be decreased"
  /categories:
    get:
      tags:
        - categories
      summary: Gets all categories
      description: Returns all categories owned by the user
      operationId: categories(get)
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/page"
          required: false
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
            - defaultLocation:
                name: 'desc'
      responses:
        "200":
          description: All categories of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        name:
                          $ref: "#/components/schemas/name"
                        defaultLocation:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                  pages:
                    $ref: "#/components/schemas/pages"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - categories
      summary: Creates a new category
      description: Creates a new category
      operationId: categories(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultLocationId
      responses:
        "201":
          description: Category created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: category cannot be created"
  /categories/{categoryId}:
    get:
      tags:
        - categories
      summary: Gets category
      description: Returns category's name and defaultLocationId
      operationId: categories/[categoryId](get)
      parameters:
        - in: path
          name: categoryId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: Name and defaultLocationId
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    $ref: "#/components/schemas/name"
                  defaultLocationId:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested category"
        "404":
          description: "Not Found: no categories found with specified categoryId"
    patch:
      tags:
        - categories
      summary: Modifies the category
      description: Updates the category's name and defaultLocationId
      operationId: categories/[categoryId](patch)
      parameters:
        - in: path
          name: categoryId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/name"
                defaultLocationId:
                  $ref: "#/components/schemas/id"
              required:
                - name
                - defaultLocationId
      responses:
        "204":
          description: Category updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested category"
        "404":
          description: "Not Found: no categories found with specified categoryId"
        "422":
          description: "Unprocessable Content: category cannot be updated"
  /books:
    get:
      tags:
        - books
      summary: Gets all books
      description: Returns all books owned by the user
      operationId: books(get)
      parameters:
        - in: query
          name: page
          schema:
            $ref: "#/components/schemas/page"
          required: false
        - in: query
          name: order
          schema:
            $ref: "#/components/schemas/order"
          required: false
          example:
            - name: 'asc'
            - defaultLocation:
                name: 'desc'
      responses:
        "200":
          description: All books of which the user is owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  books:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: "#/components/schemas/id"
                        category:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                        title:
                          $ref: "#/components/schemas/title"
                        location:
                          type: object
                          properties:
                            name:
                              $ref: "#/components/schemas/name"
                  pages:
                    $ref: "#/components/schemas/pages"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
    post:
      tags:
        - books
      summary: Creates a new book
      description: Creates a new book, bulk titles with '~'
      operationId: books(post)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryId:
                  $ref: "#/components/schemas/id"
                title:
                  $ref: "#/components/schemas/name"
                locationId:
                  $ref: "#/components/schemas/id"
              required:
                - categoryId
                - title
                - locationId
      responses:
        "201":
          description: Book created succesfully
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      id:
                        $ref: "#/components/schemas/id"
                  - type: object
                    properties:
                      ids:
                        type: array
                        items:
                          $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: "Unprocessable Content: book cannot be created"
  /books/{bookId}:
    get:
      tags:
        - books
      summary: Gets book
      description: Returns book's categoryId, title and locationId
      operationId: books/[bookId](get)
      parameters:
        - in: path
          name: bookId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "200":
          description: CategoryId, title and locationId
          content:
            application/json:
              schema:
                type: object
                properties:
                  categoryId:
                    $ref: "#/components/schemas/id"
                  title:
                    $ref: "#/components/schemas/title"
                  locationId:
                    $ref: "#/components/schemas/id"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested book"
        "404":
          description: "Not Found: no books found with specified bookId"
    patch:
      tags:
        - books
      summary: Modifies the book
      description: Updates the book's categoryId, title and locationId
      operationId: books/[bookId](patch)
      parameters:
        - in: path
          name: bookId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryId:
                  $ref: "#/components/schemas/id"
                title:
                  $ref: "#/components/schemas/name"
                locationId:
                  $ref: "#/components/schemas/id"
              required:
                - categoryId
                - title
                - locationId
      responses:
        "204":
          description: Book updated successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested book"
        "404":
          description: "Not Found: no books found with specified bookId"
        "422":
          description: "Unprocessable Content: book cannot be updated"
    delete:
      tags:
        - books
      summary: Deletes book
      description: Removes the book
      operationId: books/[bookId](delete)
      parameters:
        - in: path
          name: bookId
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        "204":
          description: Book deleted succesfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: "Forbidden: requesting user does not own requested book"
        "404":
          description: "Not Found: no books found with specified bookId"